// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:expense/models/budget.dart';
import 'package:expense/models/category.dart';
import 'package:expense/models/expense.dart';
import 'package:expense/models/income.dart';
import 'package:expense/models/recurring_transaction.dart';
import 'package:expense/models/savings_goal.dart';
import 'package:expense/models/task.dart';
import 'package:expense/models/user_settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryTypeAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(IncomeAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(RecurringTypeAdapter());
    registerAdapter(SavingsGoalAdapter());
    registerAdapter(SubtaskAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryTypeAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(IncomeAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(RecurringTypeAdapter());
    registerAdapter(SavingsGoalAdapter());
    registerAdapter(SubtaskAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}
